// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:eleaning/data/services/api_keys.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: ApiKeys.firebaseAPIKey,
    appId: '1:598220850953:android:639daf57c9d8cef73a35d8',
    messagingSenderId: '598220850953',
    projectId: 'learning-ccdc6',
    storageBucket: 'learning-ccdc6.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: ApiKeys.firebaseAPIKey,
    appId: '1:598220850953:ios:ec9d763c20e628ef3a35d8',
    messagingSenderId: '598220850953',
    projectId: 'learning-ccdc6',
    storageBucket: 'learning-ccdc6.firebasestorage.app',
    iosBundleId: 'com.example.eleaning',
  );
}
